# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #1f232a\n"
"}\n"
"#leftMenuSubContainer{\n"
"    background-color:#16191d;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 2px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"#centerMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#frame_4{\n"
"    background-color: #16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"#headerContainer{\n"
"    background-color: #2c313c\n"
"}\n"
"#pistonTable{\n"
"    background-color: #16191d;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2c313c;\n"
"    border: none;\n"
"    height: 32px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.frame)
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(24, 24))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_2.addWidget(self.menuBtn)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.homeBtn.setFont(font)
        self.homeBtn.setStyleSheet("background-color: #1f232a;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/piston.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(32, 32))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_3.addWidget(self.homeBtn)
        self.dataBtn = QtWidgets.QPushButton(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataBtn.setIcon(icon2)
        self.dataBtn.setIconSize(QtCore.QSize(24, 24))
        self.dataBtn.setObjectName("dataBtn")
        self.verticalLayout_3.addWidget(self.dataBtn)
        self.reportBtn = QtWidgets.QPushButton(self.frame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBtn.setIcon(icon3)
        self.reportBtn.setIconSize(QtCore.QSize(24, 24))
        self.reportBtn.setObjectName("reportBtn")
        self.verticalLayout_3.addWidget(self.reportBtn)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settingsBtn = QtWidgets.QPushButton(self.frame_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon4)
        self.settingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_4.addWidget(self.settingsBtn)
        self.infoBtn = QtWidgets.QPushButton(self.frame_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoBtn.setIcon(icon5)
        self.infoBtn.setIconSize(QtCore.QSize(24, 24))
        self.infoBtn.setObjectName("infoBtn")
        self.verticalLayout_4.addWidget(self.infoBtn)
        self.helpBtn = QtWidgets.QPushButton(self.frame_3)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon6)
        self.helpBtn.setIconSize(QtCore.QSize(24, 24))
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_4.addWidget(self.helpBtn)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.leftMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer, 0, QtCore.Qt.AlignLeft)
        self.centerMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.centerMenuContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.centerMenuContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.centerMenuContainer.setStyleSheet("background-color:#16191d;")
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.centerMenuSubContainer = QtWidgets.QWidget(self.centerMenuContainer)
        self.centerMenuSubContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.centerMenuSubContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.centerMenuSubContainer.setStyleSheet("background-color: #2c313c;\n"
"")
        self.centerMenuSubContainer.setObjectName("centerMenuSubContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centerMenuSubContainer)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.addFormContainer = QtWidgets.QFrame(self.centerMenuSubContainer)
        self.addFormContainer.setStyleSheet("border-radius: 20px;\n"
"background-color: #16191d;")
        self.addFormContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addFormContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addFormContainer.setObjectName("addFormContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.addFormContainer)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_8 = QtWidgets.QFrame(self.addFormContainer)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_18.addWidget(self.frame_8)
        self.addformFrame = QtWidgets.QFrame(self.addFormContainer)
        self.addformFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addformFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addformFrame.setObjectName("addformFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.addformFrame)
        self.verticalLayout_17.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_17.setSpacing(9)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_13 = QtWidgets.QFrame(self.addformFrame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.brandLine = QtWidgets.QLineEdit(self.frame_13)
        self.brandLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.brandLine.setObjectName("brandLine")
        self.verticalLayout_12.addWidget(self.brandLine)
        self.verticalLayout_17.addWidget(self.frame_13)
        self.frame_17 = QtWidgets.QFrame(self.addformFrame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.frame_17)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.tactLine = QtWidgets.QLineEdit(self.frame_17)
        self.tactLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.tactLine.setObjectName("tactLine")
        self.verticalLayout_16.addWidget(self.tactLine)
        self.verticalLayout_17.addWidget(self.frame_17)
        self.frame_14 = QtWidgets.QFrame(self.addformFrame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.modelLine = QtWidgets.QLineEdit(self.frame_14)
        self.modelLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.modelLine.setObjectName("modelLine")
        self.verticalLayout_13.addWidget(self.modelLine)
        self.verticalLayout_17.addWidget(self.frame_14)
        self.frame_16 = QtWidgets.QFrame(self.addformFrame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_16)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.pistonCodeLine = QtWidgets.QLineEdit(self.frame_16)
        self.pistonCodeLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.pistonCodeLine.setObjectName("pistonCodeLine")
        self.verticalLayout_15.addWidget(self.pistonCodeLine)
        self.verticalLayout_17.addWidget(self.frame_16)
        self.frame_15 = QtWidgets.QFrame(self.addformFrame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.frame_15)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.diameterLine = QtWidgets.QLineEdit(self.frame_15)
        self.diameterLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.diameterLine.setObjectName("diameterLine")
        self.verticalLayout_14.addWidget(self.diameterLine)
        self.verticalLayout_17.addWidget(self.frame_15)
        self.frame_12 = QtWidgets.QFrame(self.addformFrame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.pinDiameterLine = QtWidgets.QLineEdit(self.frame_12)
        self.pinDiameterLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.pinDiameterLine.setObjectName("pinDiameterLine")
        self.verticalLayout_11.addWidget(self.pinDiameterLine)
        self.verticalLayout_17.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.addformFrame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.totalHeightLine = QtWidgets.QLineEdit(self.frame_11)
        self.totalHeightLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.totalHeightLine.setObjectName("totalHeightLine")
        self.verticalLayout_9.addWidget(self.totalHeightLine)
        self.verticalLayout_17.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.addformFrame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.compressionLine = QtWidgets.QLineEdit(self.frame_10)
        self.compressionLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.compressionLine.setObjectName("compressionLine")
        self.verticalLayout_7.addWidget(self.compressionLine)
        self.verticalLayout_17.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.addformFrame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.oversizeLine = QtWidgets.QLineEdit(self.frame_9)
        self.oversizeLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.oversizeLine.setObjectName("oversizeLine")
        self.verticalLayout_6.addWidget(self.oversizeLine)
        self.verticalLayout_17.addWidget(self.frame_9)
        self.verticalLayout_18.addWidget(self.addformFrame)
        self.frame_4 = QtWidgets.QFrame(self.addFormContainer)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.insertBtn = QtWidgets.QPushButton(self.frame_4)
        self.insertBtn.setStyleSheet("background-color: green;\n"
"border-radius: 20px;\n"
"font-size: 14px;\n"
"padding: 10px;\n"
"")
        self.insertBtn.setObjectName("insertBtn")
        self.verticalLayout_19.addWidget(self.insertBtn)
        self.verticalLayout_18.addWidget(self.frame_4)
        self.verticalLayout_8.addWidget(self.addFormContainer)
        self.verticalLayout_5.addWidget(self.centerMenuSubContainer)
        self.horizontalLayout.addWidget(self.centerMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.headerContainer = QtWidgets.QWidget(self.mainBodyContainer)
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.headerContainer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.editBtn = QtWidgets.QPushButton(self.frame_5)
        self.editBtn.setStyleSheet("QPushButton{\n"
"  background-color: #EA4C89;\n"
"  border-radius: 8px;\n"
"  border-style: none;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  height:20px;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 10px 16px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: color 100ms;\n"
"  vertical-align: baseline;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #F082AC;\n"
"}")
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_7.addWidget(self.editBtn)
        self.deleteBtn = QtWidgets.QPushButton(self.frame_5)
        self.deleteBtn.setStyleSheet("QPushButton{\n"
"  background-color: #EA4C89;\n"
"  border-radius: 8px;\n"
"  border-style: none;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  height:20px;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 10px 16px;\n"
"  position: relative;\n"
"  transition: color 100ms;\n"
"  text-align: center;\n"
"  user-select: none;\n"
"  text-decoration: none;\n"
"  vertical-align: baseline;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #F082AC;\n"
"}")
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout_7.addWidget(self.deleteBtn)
        self.horizontalLayout_5.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.headerContainer)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.searchBtn = QtWidgets.QPushButton(self.frame_6)
        self.searchBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBtn.setIcon(icon7)
        self.searchBtn.setIconSize(QtCore.QSize(24, 24))
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout_6.addWidget(self.searchBtn)
        self.searchLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.horizontalLayout_6.addWidget(self.searchLabel)
        self.horizontalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.headerContainer)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeBtn = QtWidgets.QPushButton(self.frame_7)
        self.minimizeBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.minimizeBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon8)
        self.minimizeBtn.setIconSize(QtCore.QSize(16, 16))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_4.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.frame_7)
        self.restoreBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.restoreBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon9)
        self.restoreBtn.setIconSize(QtCore.QSize(16, 16))
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_4.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame_7)
        self.closeBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.closeBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon10)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.headerContainer)
        self.mainBodyContent = QtWidgets.QWidget(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContent.sizePolicy().hasHeightForWidth())
        self.mainBodyContent.setSizePolicy(sizePolicy)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mainBodyContent)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentsContainer = QtWidgets.QWidget(self.mainBodyContent)
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.mainContentsContainer)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pistonTable = QtWidgets.QTableWidget(self.mainContentsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pistonTable.sizePolicy().hasHeightForWidth())
        self.pistonTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pistonTable.setFont(font)
        self.pistonTable.setAutoFillBackground(False)
        self.pistonTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.pistonTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.pistonTable.setObjectName("pistonTable")
        self.pistonTable.setColumnCount(9)
        self.pistonTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.pistonTable.setHorizontalHeaderItem(8, item)
        self.pistonTable.horizontalHeader().setCascadingSectionResizes(True)
        self.pistonTable.horizontalHeader().setSortIndicatorShown(True)
        self.pistonTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_9.addWidget(self.pistonTable)
        self.horizontalLayout_8.addWidget(self.mainContentsContainer)
        self.verticalLayout_10.addWidget(self.mainBodyContent)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuBtn.setToolTip(_translate("MainWindow", "Menu"))
        self.homeBtn.setToolTip(_translate("MainWindow", "Home"))
        self.homeBtn.setText(_translate("MainWindow", "Pistons"))
        self.dataBtn.setToolTip(_translate("MainWindow", "Data Analysis"))
        self.dataBtn.setText(_translate("MainWindow", "Data Analysis"))
        self.reportBtn.setToolTip(_translate("MainWindow", "View Reports"))
        self.reportBtn.setText(_translate("MainWindow", "Reports"))
        self.settingsBtn.setToolTip(_translate("MainWindow", "Go to settings"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.infoBtn.setToolTip(_translate("MainWindow", "Information about the app"))
        self.infoBtn.setText(_translate("MainWindow", "Info"))
        self.helpBtn.setToolTip(_translate("MainWindow", "Get more help"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.label_3.setText(_translate("MainWindow", "Add New Piston"))
        self.label_9.setText(_translate("MainWindow", "Brand"))
        self.label_13.setText(_translate("MainWindow", "Tact"))
        self.label_10.setText(_translate("MainWindow", "Model"))
        self.label_12.setText(_translate("MainWindow", "Piston Code"))
        self.label_11.setText(_translate("MainWindow", "Diameter(mm)"))
        self.label_8.setText(_translate("MainWindow", "Pin Diameter(mm)"))
        self.label_7.setText(_translate("MainWindow", "Total Height(mm)"))
        self.label_4.setText(_translate("MainWindow", "Compression Height(mm)"))
        self.label.setText(_translate("MainWindow", "Oversize"))
        self.insertBtn.setText(_translate("MainWindow", "Insert"))
        self.editBtn.setText(_translate("MainWindow", "Edit"))
        self.deleteBtn.setText(_translate("MainWindow", "Delete"))
        self.searchLabel.setText(_translate("MainWindow", "Search"))
        item = self.pistonTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.pistonTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.pistonTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tact"))
        item = self.pistonTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Piston Code"))
        item = self.pistonTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Diameter(mm)"))
        item = self.pistonTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Height(mm)"))
        item = self.pistonTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Pin Diameter(mm)"))
        item = self.pistonTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Compression Height(mm)"))
        item = self.pistonTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Oversize"))

