# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'are_you_sure_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alertWindow(object):
    def setupUi(self, alertWindow):
        alertWindow.setObjectName("alertWindow")
        alertWindow.resize(400, 200)
        alertWindow.setMinimumSize(QtCore.QSize(400, 200))
        alertWindow.setMaximumSize(QtCore.QSize(400, 200))
        alertWindow.setStyleSheet("background-color:#1f232a;\n"
"background-color: transparent;\n"
"border-radius:20px;")
        self.centralwidget = QtWidgets.QWidget(alertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color:#1f232a;\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainContainer = QtWidgets.QWidget(self.widget)
        self.mainContainer.setStyleSheet("background-color:#1f232a;\n"
"border-radius:20px;")
        self.mainContainer.setObjectName("mainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.mainContainer)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonsFrame = QtWidgets.QFrame(self.widget_3)
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.closeBtn = QtWidgets.QPushButton(self.buttonsFrame)
        self.closeBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.closeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.horizontalLayout_2.addWidget(self.buttonsFrame, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.mainContainer)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelContainer = QtWidgets.QWidget(self.widget_2)
        self.labelContainer.setObjectName("labelContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.labelContainer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.labelContainer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.labelContainer)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.yesBtn = QtWidgets.QPushButton(self.widget_4)
        self.yesBtn.setStyleSheet("QPushButton{\n"
"  background-color: #EA4C89;\n"
"  border-radius: 8px;\n"
"  border-style: none;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  height:20px;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 10px 16px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: color 100ms;\n"
"  vertical-align: baseline;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #F082AC;\n"
"}")
        self.yesBtn.setObjectName("yesBtn")
        self.horizontalLayout_5.addWidget(self.yesBtn)
        self.noBtn = QtWidgets.QPushButton(self.widget_4)
        self.noBtn.setStyleSheet("QPushButton{\n"
"  background-color: #EA4C89;\n"
"  border-radius: 8px;\n"
"  border-style: none;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  height:20px;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 10px 16px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: color 100ms;\n"
"  vertical-align: baseline;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #F082AC;\n"
"}")
        self.noBtn.setObjectName("noBtn")
        self.horizontalLayout_5.addWidget(self.noBtn)
        self.verticalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.mainContainer)
        self.horizontalLayout.addWidget(self.widget)
        alertWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(alertWindow)
        QtCore.QMetaObject.connectSlotsByName(alertWindow)

    def retranslateUi(self, alertWindow):
        _translate = QtCore.QCoreApplication.translate
        alertWindow.setWindowTitle(_translate("alertWindow", "MainWindow"))
        self.label.setText(_translate("alertWindow", "Are you sure to delete the selected item?"))
        self.yesBtn.setText(_translate("alertWindow", "Yes"))
        self.noBtn.setText(_translate("alertWindow", "No"))

