# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        script_dir = os.path.dirname(os.path.abspath(__file__))
        icon_path_exit = os.path.join(script_dir, "..", "icons", "x.svg")
        icon_path_maximize = os.path.join(script_dir, "..", "icons", "square.svg")
        icon_path_minimize = os.path.join(script_dir, "..", "icons", "minus.svg")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 924)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(398, 924))
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #1f232a\n"
"}\n"
"#leftMenuSubContainer{\n"
"    background-color:#16191d;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 2px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"#centerMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#frame_4{\n"
"    background-color: #16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"#headerContainer{\n"
"    background-color: #2c313c\n"
"}\n"
"#pistonTable{\n"
"    background-color: #16191d;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2c313c;\n"
"    border: none;\n"
"    height: 32px;\n"
"}\n"
"#LineEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeBtn = QtWidgets.QPushButton(self.frame)
        self.minimizeBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.minimizeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(icon_path_minimize), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon)
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_2.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.frame)
        self.restoreBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.restoreBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(icon_path_maximize), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon1)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_2.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame)
        self.closeBtn.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(255, 0, 127)\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(icon_path_exit), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.horizontalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.editFormFrame = QtWidgets.QFrame(self.widget_5)
        self.editFormFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editFormFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editFormFrame.setObjectName("editFormFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.editFormFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_22 = QtWidgets.QFrame(self.editFormFrame)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(self.frame_22)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_69 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_5.addWidget(self.label_69)
        self.pistonCodeLine = QtWidgets.QLineEdit(self.frame_8)
        self.pistonCodeLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.pistonCodeLine.setObjectName("pistonCodeLine")
        self.verticalLayout_5.addWidget(self.pistonCodeLine)
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_22)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_70 = QtWidgets.QLabel(self.frame_9)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_7.addWidget(self.label_70)
        self.codePrevValue = QtWidgets.QLabel(self.frame_9)
        self.codePrevValue.setObjectName("codePrevValue")
        self.horizontalLayout_7.addWidget(self.codePrevValue)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_22)
        self.this_2 = QtWidgets.QFrame(self.editFormFrame)
        self.this_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_2.setObjectName("this_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.this_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.this_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_72 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_6.addWidget(self.label_72)
        self.brandLine = QtWidgets.QLineEdit(self.frame_10)
        self.brandLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.brandLine.setObjectName("brandLine")
        self.verticalLayout_6.addWidget(self.brandLine)
        self.horizontalLayout_9.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.this_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_73 = QtWidgets.QLabel(self.frame_11)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_10.addWidget(self.label_73)
        self.brandPrevValue = QtWidgets.QLabel(self.frame_11)
        self.brandPrevValue.setObjectName("brandPrevValue")
        self.horizontalLayout_10.addWidget(self.brandPrevValue)
        self.horizontalLayout_9.addWidget(self.frame_11)
        self.verticalLayout_2.addWidget(self.this_2)
        self.this_9 = QtWidgets.QFrame(self.editFormFrame)
        self.this_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_9.setObjectName("this_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.this_9)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_25 = QtWidgets.QFrame(self.this_9)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_93 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_13.addWidget(self.label_93)
        self.modelLine = QtWidgets.QLineEdit(self.frame_25)
        self.modelLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.modelLine.setObjectName("modelLine")
        self.verticalLayout_13.addWidget(self.modelLine)
        self.horizontalLayout_23.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.this_9)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_94 = QtWidgets.QLabel(self.frame_26)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_24.addWidget(self.label_94)
        self.modelPrevValue = QtWidgets.QLabel(self.frame_26)
        self.modelPrevValue.setObjectName("modelPrevValue")
        self.horizontalLayout_24.addWidget(self.modelPrevValue)
        self.horizontalLayout_23.addWidget(self.frame_26)
        self.verticalLayout_2.addWidget(self.this_9)
        self.this_8 = QtWidgets.QFrame(self.editFormFrame)
        self.this_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_8.setObjectName("this_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.this_8)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_23 = QtWidgets.QFrame(self.this_8)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_90 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_12.addWidget(self.label_90)
        self.diameterLine = QtWidgets.QLineEdit(self.frame_23)
        self.diameterLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.diameterLine.setObjectName("diameterLine")
        self.verticalLayout_12.addWidget(self.diameterLine)
        self.horizontalLayout_21.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.this_8)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_91 = QtWidgets.QLabel(self.frame_24)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_22.addWidget(self.label_91)
        self.diameterPrevValue = QtWidgets.QLabel(self.frame_24)
        self.diameterPrevValue.setObjectName("diameterPrevValue")
        self.horizontalLayout_22.addWidget(self.diameterPrevValue)
        self.horizontalLayout_21.addWidget(self.frame_24)
        self.verticalLayout_2.addWidget(self.this_8)
        self.this_7 = QtWidgets.QFrame(self.editFormFrame)
        self.this_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_7.setObjectName("this_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.this_7)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_20 = QtWidgets.QFrame(self.this_7)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_87 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_11.addWidget(self.label_87)
        self.pinDiameterLine = QtWidgets.QLineEdit(self.frame_20)
        self.pinDiameterLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.pinDiameterLine.setObjectName("pinDiameterLine")
        self.verticalLayout_11.addWidget(self.pinDiameterLine)
        self.horizontalLayout_19.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.this_7)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_88 = QtWidgets.QLabel(self.frame_21)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_20.addWidget(self.label_88)
        self.pinDiameterPrevValue = QtWidgets.QLabel(self.frame_21)
        self.pinDiameterPrevValue.setObjectName("pinDiameterPrevValue")
        self.horizontalLayout_20.addWidget(self.pinDiameterPrevValue)
        self.horizontalLayout_19.addWidget(self.frame_21)
        self.verticalLayout_2.addWidget(self.this_7)
        self.this_6 = QtWidgets.QFrame(self.editFormFrame)
        self.this_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_6.setObjectName("this_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.this_6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_18 = QtWidgets.QFrame(self.this_6)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_84 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_10.addWidget(self.label_84)
        self.totalHeightLine = QtWidgets.QLineEdit(self.frame_18)
        self.totalHeightLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.totalHeightLine.setObjectName("totalHeightLine")
        self.verticalLayout_10.addWidget(self.totalHeightLine)
        self.horizontalLayout_17.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.this_6)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_85 = QtWidgets.QLabel(self.frame_19)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_18.addWidget(self.label_85)
        self.totalHeightPrevValue = QtWidgets.QLabel(self.frame_19)
        self.totalHeightPrevValue.setObjectName("totalHeightPrevValue")
        self.horizontalLayout_18.addWidget(self.totalHeightPrevValue)
        self.horizontalLayout_17.addWidget(self.frame_19)
        self.verticalLayout_2.addWidget(self.this_6)
        self.this_5 = QtWidgets.QFrame(self.editFormFrame)
        self.this_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_5.setObjectName("this_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.this_5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_16 = QtWidgets.QFrame(self.this_5)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_81 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_9.addWidget(self.label_81)
        self.compressionLine = QtWidgets.QLineEdit(self.frame_16)
        self.compressionLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.compressionLine.setObjectName("compressionLine")
        self.verticalLayout_9.addWidget(self.compressionLine)
        self.horizontalLayout_15.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.this_5)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_82 = QtWidgets.QLabel(self.frame_17)
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_16.addWidget(self.label_82)
        self.compressionPrevValue = QtWidgets.QLabel(self.frame_17)
        self.compressionPrevValue.setObjectName("compressionPrevValue")
        self.horizontalLayout_16.addWidget(self.compressionPrevValue)
        self.horizontalLayout_15.addWidget(self.frame_17)
        self.verticalLayout_2.addWidget(self.this_5)
        self.this_4 = QtWidgets.QFrame(self.editFormFrame)
        self.this_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_4.setObjectName("this_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.this_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_14 = QtWidgets.QFrame(self.this_4)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_78 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_8.addWidget(self.label_78)
        self.tactLine = QtWidgets.QLineEdit(self.frame_14)
        self.tactLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.tactLine.setObjectName("tactLine")
        self.verticalLayout_8.addWidget(self.tactLine)
        self.horizontalLayout_13.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.this_4)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_79 = QtWidgets.QLabel(self.frame_15)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_14.addWidget(self.label_79)
        self.tactPrevValue = QtWidgets.QLabel(self.frame_15)
        self.tactPrevValue.setObjectName("tactPrevValue")
        self.horizontalLayout_14.addWidget(self.tactPrevValue)
        self.horizontalLayout_13.addWidget(self.frame_15)
        self.verticalLayout_2.addWidget(self.this_4)
        self.this_3 = QtWidgets.QFrame(self.editFormFrame)
        self.this_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.this_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.this_3.setObjectName("this_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.this_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.this_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_75 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_7.addWidget(self.label_75)
        self.oversizeLine = QtWidgets.QLineEdit(self.frame_12)
        self.oversizeLine.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 1px;\n"
"")
        self.oversizeLine.setObjectName("oversizeLine")
        self.verticalLayout_7.addWidget(self.oversizeLine)
        self.horizontalLayout_11.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.this_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_76 = QtWidgets.QLabel(self.frame_13)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_12.addWidget(self.label_76)
        self.oversizePrevValue = QtWidgets.QLabel(self.frame_13)
        self.oversizePrevValue.setObjectName("oversizePrevValue")
        self.horizontalLayout_12.addWidget(self.oversizePrevValue)
        self.horizontalLayout_11.addWidget(self.frame_13)
        self.verticalLayout_2.addWidget(self.this_3)
        self.searchBtn = QtWidgets.QPushButton(self.editFormFrame)
        self.searchBtn.setStyleSheet("QPushButton{\n"
"  background-color: #EA4C89;\n"
"  border-radius: 8px;\n"
"  border-style: none;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  height:20px;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 10px 16px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: color 100ms;\n"
"  vertical-align: baseline;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #F082AC;\n"
"}")
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout_2.addWidget(self.searchBtn)
        self.verticalLayout_3.addWidget(self.editFormFrame)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_14.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Moto Parts"))
        self.label_69.setText(_translate("MainWindow", "Piston Code"))
        self.label_70.setText(_translate("MainWindow", "Previous :"))
        self.codePrevValue.setText(_translate("MainWindow", "Value"))
        self.label_72.setText(_translate("MainWindow", "Brand"))
        self.label_73.setText(_translate("MainWindow", "Previous :"))
        self.brandPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_93.setText(_translate("MainWindow", "Model"))
        self.label_94.setText(_translate("MainWindow", "Previous :"))
        self.modelPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_90.setText(_translate("MainWindow", "Diameter(mm)"))
        self.label_91.setText(_translate("MainWindow", "Previous :"))
        self.diameterPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_87.setText(_translate("MainWindow", "Pin Diameter(mm)"))
        self.label_88.setText(_translate("MainWindow", "Previous :"))
        self.pinDiameterPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_84.setText(_translate("MainWindow", "Total Height(mm)"))
        self.label_85.setText(_translate("MainWindow", "Previous :"))
        self.totalHeightPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_81.setText(_translate("MainWindow", "Compression Height(mm)"))
        self.label_82.setText(_translate("MainWindow", "Previous :"))
        self.compressionPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_78.setText(_translate("MainWindow", "Tact"))
        self.label_79.setText(_translate("MainWindow", "Previous :"))
        self.tactPrevValue.setText(_translate("MainWindow", "Value"))
        self.label_75.setText(_translate("MainWindow", "Oversize"))
        self.label_76.setText(_translate("MainWindow", "Previous :"))
        self.oversizePrevValue.setText(_translate("MainWindow", "Value"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
